name: Build C++ Project

on:
  push:
    branches:
      - main  # Change this to your target branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ pkg-config libopencv-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libexiv2-dev

    - name: Build the project
      run: |
        g++ main.cpp qrc_resources.cpp -fPIC -o main.exe `pkg-config --cflags --libs Qt5Widgets Qt5Gui Qt5Core opencv4` -lexiv2

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: ./main.exe
